AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hts

  Hollywood Theatre Scraper

Globals:
  Function:
    Timeout: 5

Resources:
  Hts:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: ./
      Handler: hts
      Runtime: go1.x
      Tracing: Active
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)
      Environment:
        Variables:
          ENVIRONMENT: production
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/HollywoodTheatreShowtimes'
  HollywoodTheatreShowtimesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: HollywoodTheatreShowtimes
      AttributeDefinitions: 
        - AttributeName: Title
          AttributeType: S
        - AttributeName: DateTime
          AttributeType: S
      KeySchema: 
        - AttributeName: Title
          KeyType: HASH
        - AttributeName: DateTime
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 10